"""Let another application read a library on its owner's behalf

Revision ID: 03fa7e161674
Revises: 8b8fe12270c6
Create Date: 2026-08-27 08:39:55.500671

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03fa7e161674"
down_revision: str | Sequence[str] | None = "8b8fe12270c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_clients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("secret_hash", sa.String(length=255), nullable=True),
        sa.Column("redirect_uris", sa.Text(), nullable=False),
        sa.Column("scopes", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("disabled_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("oauth_clients", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_oauth_clients_client_id"), ["client_id"], unique=True)

    op.create_table(
        "oauth_signing_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kid", sa.String(length=64), nullable=False),
        sa.Column("private_pem", sa.Text(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("retired_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("oauth_signing_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_oauth_signing_keys_kid"), ["kid"], unique=True)

    op.create_table(
        "oauth_authorization_requests",
        sa.Column("handle", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("redirect_uri", sa.String(length=500), nullable=False),
        sa.Column("scopes", sa.String(length=255), nullable=False),
        sa.Column("state", sa.String(length=255), nullable=False),
        sa.Column("code_challenge", sa.String(length=128), nullable=False),
        sa.Column("nonce", sa.String(length=255), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["oauth_clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("handle"),
    )
    with op.batch_alter_table("oauth_authorization_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_oauth_authorization_requests_client_id"), ["client_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_oauth_authorization_requests_expires"), ["expires"], unique=False
        )

    op.create_table(
        "oauth_grants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("scopes", sa.String(length=255), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "approved_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["client_id"], ["oauth_clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "client_id", name="uq_oauth_grant"),
    )
    with op.batch_alter_table("oauth_grants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_oauth_grants_client_id"), ["client_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_oauth_grants_user_id"), ["user_id"], unique=False)

    op.create_table(
        "oauth_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("grant_id", sa.Integer(), nullable=False),
        sa.Column("redirect_uri", sa.String(length=500), nullable=False),
        sa.Column("scopes", sa.String(length=255), nullable=False),
        sa.Column("code_challenge", sa.String(length=128), nullable=False),
        sa.Column("nonce", sa.String(length=255), nullable=False),
        sa.Column("family", sa.String(length=64), nullable=False),
        sa.Column(
            "authenticated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["grant_id"], ["oauth_grants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("oauth_codes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_oauth_codes_code_hash"), ["code_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_oauth_codes_expires"), ["expires"], unique=False)
        batch_op.create_index(batch_op.f("ix_oauth_codes_family"), ["family"], unique=False)
        batch_op.create_index(batch_op.f("ix_oauth_codes_grant_id"), ["grant_id"], unique=False)

    op.create_table(
        "oauth_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=8), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("grant_id", sa.Integer(), nullable=False),
        sa.Column("family", sa.String(length=64), nullable=False),
        sa.Column("scopes", sa.String(length=255), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["grant_id"], ["oauth_grants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("oauth_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_oauth_tokens_expires"), ["expires"], unique=False)
        batch_op.create_index(batch_op.f("ix_oauth_tokens_family"), ["family"], unique=False)
        batch_op.create_index(batch_op.f("ix_oauth_tokens_grant_id"), ["grant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_oauth_tokens_kind"), ["kind"], unique=False)
        batch_op.create_index(batch_op.f("ix_oauth_tokens_token_hash"), ["token_hash"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("oauth_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_tokens_token_hash"))
        batch_op.drop_index(batch_op.f("ix_oauth_tokens_kind"))
        batch_op.drop_index(batch_op.f("ix_oauth_tokens_grant_id"))
        batch_op.drop_index(batch_op.f("ix_oauth_tokens_family"))
        batch_op.drop_index(batch_op.f("ix_oauth_tokens_expires"))

    op.drop_table("oauth_tokens")
    with op.batch_alter_table("oauth_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_codes_grant_id"))
        batch_op.drop_index(batch_op.f("ix_oauth_codes_family"))
        batch_op.drop_index(batch_op.f("ix_oauth_codes_expires"))
        batch_op.drop_index(batch_op.f("ix_oauth_codes_code_hash"))

    op.drop_table("oauth_codes")
    with op.batch_alter_table("oauth_grants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_grants_user_id"))
        batch_op.drop_index(batch_op.f("ix_oauth_grants_client_id"))

    op.drop_table("oauth_grants")
    with op.batch_alter_table("oauth_authorization_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_authorization_requests_expires"))
        batch_op.drop_index(batch_op.f("ix_oauth_authorization_requests_client_id"))

    op.drop_table("oauth_authorization_requests")
    with op.batch_alter_table("oauth_signing_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_signing_keys_kid"))

    op.drop_table("oauth_signing_keys")
    with op.batch_alter_table("oauth_clients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_clients_client_id"))

    op.drop_table("oauth_clients")
    # ### end Alembic commands ###
