"""Create the initial schema

Revision ID: 3f85f6c3dad4
Revises:
Create Date: 2026-07-31 14:57:16.516996

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f85f6c3dad4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "libraries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("USER", "GROUP", name="librarytype", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("public", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type", "owner_id", name="uq_libraries_type_owner"),
    )
    with op.batch_alter_table("libraries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_libraries_owner_id"), ["owner_id"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("library_read", sa.Boolean(), nullable=False),
        sa.Column("library_write", sa.Boolean(), nullable=False),
        sa.Column("notes_read", sa.Boolean(), nullable=False),
        sa.Column("files_read", sa.Boolean(), nullable=False),
        sa.Column("all_groups_read", sa.Boolean(), nullable=False),
        sa.Column("all_groups_write", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_keys_key"), ["key"], unique=True)
        batch_op.create_index(batch_op.f("ix_api_keys_user_id"), ["user_id"], unique=False)

    op.create_table(
        "collections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=8), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "date_added",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "date_modified",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "server_date_modified",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["collections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("library_id", "key", name="uq_collections_library_key"),
    )
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_collections_deleted"), ["deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_collections_library_id"), ["library_id"], unique=False)
        batch_op.create_index(
            "ix_collections_library_version", ["library_id", "version"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_collections_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_collections_server_date_modified"),
            ["server_date_modified"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_collections_version"), ["version"], unique=False)

    op.create_table(
        "deleted_objects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("object_type", sa.String(length=16), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "deleted", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "library_id", "object_type", "key", name="uq_deleted_objects_library_type_key"
        ),
    )
    with op.batch_alter_table("deleted_objects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deleted_objects_library_id"), ["library_id"], unique=False
        )
        batch_op.create_index(
            "ix_deleted_objects_library_version", ["library_id", "version"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_deleted_objects_version"), ["version"], unique=False)

    op.create_table(
        "group_members",
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("library_id", "user_id"),
    )
    op.create_table(
        "groups",
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("library_editing", sa.String(length=16), nullable=False),
        sa.Column("library_reading", sa.String(length=16), nullable=False),
        sa.Column("file_editing", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("library_id"),
    )
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=8), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("item_type", sa.String(length=32), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("sort_title", sa.String(length=500), nullable=False),
        sa.Column("sort_creator", sa.String(length=255), nullable=False),
        sa.Column("sort_date", sa.String(length=32), nullable=False),
        sa.Column(
            "date_added",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "date_modified",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "server_date_modified",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("library_id", "key", name="uq_items_library_key"),
    )
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_items_deleted"), ["deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_items_item_type"), ["item_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_items_library_id"), ["library_id"], unique=False)
        batch_op.create_index("ix_items_library_version", ["library_id", "version"], unique=False)
        batch_op.create_index(batch_op.f("ix_items_parent_id"), ["parent_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_items_server_date_modified"), ["server_date_modified"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_items_sort_creator"), ["sort_creator"], unique=False)
        batch_op.create_index(batch_op.f("ix_items_sort_date"), ["sort_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_items_sort_title"), ["sort_title"], unique=False)
        batch_op.create_index(batch_op.f("ix_items_version"), ["version"], unique=False)

    op.create_table(
        "searches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=8), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "date_added",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "date_modified",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "server_date_modified",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("library_id", "key", name="uq_searches_library_key"),
    )
    with op.batch_alter_table("searches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_searches_deleted"), ["deleted"], unique=False)
        batch_op.create_index(batch_op.f("ix_searches_library_id"), ["library_id"], unique=False)
        batch_op.create_index(
            "ix_searches_library_version", ["library_id", "version"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_searches_server_date_modified"), ["server_date_modified"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_searches_version"), ["version"], unique=False)

    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("library_id", "name", name="uq_settings_library_name"),
    )
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_settings_library_id"), ["library_id"], unique=False)
        batch_op.create_index(
            "ix_settings_library_version", ["library_id", "version"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_settings_version"), ["version"], unique=False)

    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "date_added",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "date_modified",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "server_date_modified",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("library_id", "key", name="uq_tags_library_key"),
        sa.UniqueConstraint("library_id", "name", "type", name="uq_tags_library_name_type"),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tags_library_id"), ["library_id"], unique=False)
        batch_op.create_index("ix_tags_library_version", ["library_id", "version"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tags_server_date_modified"), ["server_date_modified"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_tags_version"), ["version"], unique=False)

    op.create_table(
        "write_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(length=32), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("library_id", "token", name="uq_write_tokens_library_token"),
    )
    with op.batch_alter_table("write_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_write_tokens_created"), ["created"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_write_tokens_library_id"), ["library_id"], unique=False
        )

    op.create_table(
        "api_key_group_access",
        sa.Column("api_key_id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("read", sa.Boolean(), nullable=False),
        sa.Column("write", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_keys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("api_key_id", "library_id"),
    )
    op.create_table(
        "collection_items",
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("collection_id", "item_id"),
    )
    op.create_table(
        "item_creators",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("creator_type", sa.String(length=32), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("item_id", "position"),
    )
    op.create_table(
        "item_fields",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("field", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("item_id", "field"),
    )
    op.create_table(
        "item_relations",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("predicate", sa.String(length=64), nullable=False),
        sa.Column("object", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.PrimaryKeyConstraint("item_id", "predicate", "object"),
    )
    op.create_table(
        "item_tags",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("item_id", "tag_id"),
    )
    op.create_table(
        "search_conditions",
        sa.Column("search_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("condition", sa.String(length=64), nullable=False),
        sa.Column("operator", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["search_id"],
            ["searches.id"],
        ),
        sa.PrimaryKeyConstraint("search_id", "position"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("search_conditions")
    op.drop_table("item_tags")
    op.drop_table("item_relations")
    op.drop_table("item_fields")
    op.drop_table("item_creators")
    op.drop_table("collection_items")
    op.drop_table("api_key_group_access")
    with op.batch_alter_table("write_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_write_tokens_library_id"))
        batch_op.drop_index(batch_op.f("ix_write_tokens_created"))

    op.drop_table("write_tokens")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tags_version"))
        batch_op.drop_index(batch_op.f("ix_tags_server_date_modified"))
        batch_op.drop_index("ix_tags_library_version")
        batch_op.drop_index(batch_op.f("ix_tags_library_id"))

    op.drop_table("tags")
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_settings_version"))
        batch_op.drop_index("ix_settings_library_version")
        batch_op.drop_index(batch_op.f("ix_settings_library_id"))

    op.drop_table("settings")
    with op.batch_alter_table("searches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_searches_version"))
        batch_op.drop_index(batch_op.f("ix_searches_server_date_modified"))
        batch_op.drop_index("ix_searches_library_version")
        batch_op.drop_index(batch_op.f("ix_searches_library_id"))
        batch_op.drop_index(batch_op.f("ix_searches_deleted"))

    op.drop_table("searches")
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_items_version"))
        batch_op.drop_index(batch_op.f("ix_items_sort_title"))
        batch_op.drop_index(batch_op.f("ix_items_sort_date"))
        batch_op.drop_index(batch_op.f("ix_items_sort_creator"))
        batch_op.drop_index(batch_op.f("ix_items_server_date_modified"))
        batch_op.drop_index(batch_op.f("ix_items_parent_id"))
        batch_op.drop_index("ix_items_library_version")
        batch_op.drop_index(batch_op.f("ix_items_library_id"))
        batch_op.drop_index(batch_op.f("ix_items_item_type"))
        batch_op.drop_index(batch_op.f("ix_items_deleted"))

    op.drop_table("items")
    op.drop_table("groups")
    op.drop_table("group_members")
    with op.batch_alter_table("deleted_objects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deleted_objects_version"))
        batch_op.drop_index("ix_deleted_objects_library_version")
        batch_op.drop_index(batch_op.f("ix_deleted_objects_library_id"))

    op.drop_table("deleted_objects")
    with op.batch_alter_table("collections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_collections_version"))
        batch_op.drop_index(batch_op.f("ix_collections_server_date_modified"))
        batch_op.drop_index(batch_op.f("ix_collections_parent_id"))
        batch_op.drop_index("ix_collections_library_version")
        batch_op.drop_index(batch_op.f("ix_collections_library_id"))
        batch_op.drop_index(batch_op.f("ix_collections_deleted"))

    op.drop_table("collections")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_user_id"))
        batch_op.drop_index(batch_op.f("ix_api_keys_key"))

    op.drop_table("api_keys")
    op.drop_table("users")
    with op.batch_alter_table("libraries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_libraries_owner_id"))

    op.drop_table("libraries")
    # ### end Alembic commands ###
