"""Record when and where a key was last used

Revision ID: 5452707b9c08
Revises: 70dace2b77f5
Create Date: 2026-08-03 23:17:22.847093

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5452707b9c08"
down_revision: str | Sequence[str] | None = "70dace2b77f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_used", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("last_address", sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column("last_user_agent", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_column("last_user_agent")
        batch_op.drop_column("last_address")
        batch_op.drop_column("last_used")

    # ### end Alembic commands ###
