"""Add notifications and group invitations

``totp_credentials.confirmed`` arrives as true for every row that already
exists, and only for those. Before this revision there was no unconfirmed
state: a credential was written only once it was working, and sign-in required
it. Adding the column with the model's own default of false would therefore
turn off the second factor for everyone who had one, on upgrade, silently --
which is the failure mode a security feature can least afford. The server
default is dropped again immediately afterwards so that new rows have to say
what they are.

Revision ID: 593e1a25c02a
Revises: cf1c30dc2b55
Create Date: 2026-08-03 15:42:48.033291

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "593e1a25c02a"
down_revision: str | Sequence[str] | None = "cf1c30dc2b55"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("invited_by", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.Column("answered", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_invitations_email"), ["email"], unique=False)
        batch_op.create_index(batch_op.f("ix_invitations_expires"), ["expires"], unique=False)
        batch_op.create_index(batch_op.f("ix_invitations_library_id"), ["library_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_invitations_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_invitations_token_hash"), ["token_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_invitations_user_id"), ["user_id"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("invitation_id", sa.Integer(), nullable=True),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("read", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["invitation_id"], ["invitations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notifications_created"), ["created"], unique=False)
        batch_op.create_index(batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False)

    with op.batch_alter_table("totp_credentials", schema=None) as batch_op:
        # See the module docstring: true for existing rows, because every
        # credential written before this revision was already in force.
        batch_op.add_column(
            sa.Column("confirmed", sa.Boolean(), nullable=False, server_default=sa.true())
        )

    # A separate block on purpose. SQLite's batch mode rebuilds the table from
    # the operation list, so dropping the default in the same block builds the
    # new table without one and then copies rows that have no value for the
    # column -- which fails on NOT NULL for every existing enrolment. Done
    # after, the column exists and is carried across.
    with op.batch_alter_table("totp_credentials", schema=None) as batch_op:
        batch_op.alter_column("confirmed", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("totp_credentials", schema=None) as batch_op:
        batch_op.drop_column("confirmed")

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_created"))

    op.drop_table("notifications")
    with op.batch_alter_table("invitations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invitations_user_id"))
        batch_op.drop_index(batch_op.f("ix_invitations_token_hash"))
        batch_op.drop_index(batch_op.f("ix_invitations_status"))
        batch_op.drop_index(batch_op.f("ix_invitations_library_id"))
        batch_op.drop_index(batch_op.f("ix_invitations_expires"))
        batch_op.drop_index(batch_op.f("ix_invitations_email"))

    op.drop_table("invitations")
    # ### end Alembic commands ###
