"""Record which objects each change touched

Revision ID: 60dbda3ba678
Revises: 2d30e2d6d051
Create Date: 2026-08-05 17:20:23.792725

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "60dbda3ba678"
down_revision: str | Sequence[str] | None = "2d30e2d6d051"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_activity_objects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(["activity_id"], ["group_activity.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("group_activity_objects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_group_activity_objects_activity_id"), ["activity_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_activity_objects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_group_activity_objects_activity_id"))

    op.drop_table("group_activity_objects")
    # ### end Alembic commands ###
