"""Confine an OAuth grant to particular libraries and collections

The rows say where a grant reaches; ``restricted`` says whether they are the
whole of it. The flag is what an existing grant is given -- ``false``, meaning
the scopes decide alone, which is what every grant made before this meant and
still means.

Revision ID: 63853f22a780
Revises: cea1552de0ee
Create Date: 2026-08-29 18:39:47.254649

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63853f22a780"
down_revision: str | Sequence[str] | None = "cea1552de0ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth_grant_resources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("grant_id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["collection_id"], ["collections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["grant_id"], ["oauth_grants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["library_id"], ["libraries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "grant_id", "library_id", "collection_id", name="uq_oauth_grant_resource"
        ),
    )
    with op.batch_alter_table("oauth_grant_resources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_oauth_grant_resources_collection_id"), ["collection_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_oauth_grant_resources_grant_id"), ["grant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_oauth_grant_resources_library_id"), ["library_id"], unique=False
        )

    with op.batch_alter_table("oauth_grants", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("restricted", sa.Boolean(), server_default=sa.false(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("oauth_grants", schema=None) as batch_op:
        batch_op.drop_column("restricted")

    with op.batch_alter_table("oauth_grant_resources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_grant_resources_library_id"))
        batch_op.drop_index(batch_op.f("ix_oauth_grant_resources_grant_id"))
        batch_op.drop_index(batch_op.f("ix_oauth_grant_resources_collection_id"))

    op.drop_table("oauth_grant_resources")
    # ### end Alembic commands ###
