"""Record when an API key was issued

Nullable, with no server default, so keys that already exist stay null. The
column exists so somebody looking at a list of keys can tell which is which,
and backfilling every old key with the moment the migration ran would put a
date there that means nothing -- worse than admitting it is not known.

Revision ID: 70dace2b77f5
Revises: 593e1a25c02a
Create Date: 2026-08-03 23:08:56.522845

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70dace2b77f5"
down_revision: str | Sequence[str] | None = "593e1a25c02a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_column("created")

    # ### end Alembic commands ###
