"""Record the archive digest of a zipped upload

Revision ID: 76839e611393
Revises: fd194cb25c69
Create Date: 2026-07-31 20:59:50.817803

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76839e611393"
down_revision: str | Sequence[str] | None = "fd194cb25c69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("storage_uploads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("zip_md5", sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("storage_uploads", schema=None) as batch_op:
        batch_op.drop_column("zip_md5")

    # ### end Alembic commands ###
