"""Hand out permission for one file instead of the account key

Revision ID: 8b8fe12270c6
Revises: e78f6b3a6a9a
Create Date: 2026-08-27 03:58:25.687342

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b8fe12270c6"
down_revision: str | Sequence[str] | None = "e78f6b3a6a9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_downloads",
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("md5", sa.String(length=32), nullable=False),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("storage_downloads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_storage_downloads_expires"), ["expires"], unique=False)
        batch_op.create_index(batch_op.f("ix_storage_downloads_item_id"), ["item_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("storage_downloads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_storage_downloads_item_id"))
        batch_op.drop_index(batch_op.f("ix_storage_downloads_expires"))

    op.drop_table("storage_downloads")
    # ### end Alembic commands ###
