"""Let an application send somebody to sign out

Revision ID: bdc8bd3dda1b
Revises: 2c7d1a94e5b0
Create Date: 2026-08-29 03:07:00.852095

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdc8bd3dda1b"
down_revision: str | Sequence[str] | None = "2c7d1a94e5b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("oauth_clients", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("post_logout_redirect_uris", sa.Text(), server_default="", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("oauth_clients", schema=None) as batch_op:
        batch_op.drop_column("post_logout_redirect_uris")

    # ### end Alembic commands ###
