"""Let a group member choose what to be told about

Revision ID: c7042cfd41ce
Revises: ff95529bd1a0
Create Date: 2026-08-05 15:45:46.968403

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7042cfd41ce"
down_revision: str | Sequence[str] | None = "ff95529bd1a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    ``server_default`` is the adjustment autogenerate asks for and does not
    make. Every one of these is ``NOT NULL``, and a database with memberships
    already in it -- which is every database that has ever had a group -- has
    no value to put in the new columns without one. SQLite says so outright
    ("Cannot add a NOT NULL column with default value NULL") and refuses the
    upgrade.

    False is also the setting, not merely a filler: nobody has asked to be
    notified about anything, and an upgrade that turned notifications on for
    every existing member would start sending mail nobody requested.
    """
    with op.batch_alter_table("group_members", schema=None) as batch_op:
        for column in (
            "notify_items_changed",
            "notify_items_deleted",
            "notify_members_changed",
            "notify_collections_changed",
        ):
            batch_op.add_column(
                sa.Column(column, sa.Boolean(), nullable=False, server_default=sa.false())
            )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_members", schema=None) as batch_op:
        batch_op.drop_column("notify_collections_changed")
        batch_op.drop_column("notify_members_changed")
        batch_op.drop_column("notify_items_deleted")
        batch_op.drop_column("notify_items_changed")

    # ### end Alembic commands ###
