"""Authorize a device that cannot show a browser

Revision ID: cea1552de0ee
Revises: bdc8bd3dda1b
Create Date: 2026-08-29 03:18:12.450153

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cea1552de0ee"
down_revision: str | Sequence[str] | None = "bdc8bd3dda1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema.

    The foreign key is named rather than left anonymous. SQLite rebuilds the
    table and does not care, but PostgreSQL cannot drop an anonymous
    constraint, so the downgrade below would be unrunnable there.
    """
    op.create_table(
        "oauth_device_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_code_hash", sa.String(length=64), nullable=False),
        sa.Column("user_code_hash", sa.String(length=64), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("scopes", sa.String(length=255), nullable=False),
        sa.Column("grant_id", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("denied_at", sa.DateTime(), nullable=True),
        sa.Column("authenticated_at", sa.DateTime(), nullable=True),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.Column("last_polled", sa.DateTime(), nullable=True),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["client_id"], ["oauth_clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["grant_id"], ["oauth_grants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("oauth_device_codes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_oauth_device_codes_client_id"), ["client_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_oauth_device_codes_device_code_hash"), ["device_code_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_oauth_device_codes_expires"), ["expires"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_oauth_device_codes_grant_id"), ["grant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_oauth_device_codes_user_code_hash"), ["user_code_hash"], unique=True
        )

    with op.batch_alter_table("oauth_authorization_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("device_code_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_oauth_authorization_requests_device_code_id"),
            ["device_code_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_oauth_authorization_requests_device_code_id",
            "oauth_device_codes",
            ["device_code_id"],
            ["id"],
            ondelete="CASCADE",
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("oauth_authorization_requests", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_oauth_authorization_requests_device_code_id", type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_oauth_authorization_requests_device_code_id"))
        batch_op.drop_column("device_code_id")

    with op.batch_alter_table("oauth_device_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_oauth_device_codes_user_code_hash"))
        batch_op.drop_index(batch_op.f("ix_oauth_device_codes_grant_id"))
        batch_op.drop_index(batch_op.f("ix_oauth_device_codes_expires"))
        batch_op.drop_index(batch_op.f("ix_oauth_device_codes_device_code_hash"))
        batch_op.drop_index(batch_op.f("ix_oauth_device_codes_client_id"))

    op.drop_table("oauth_device_codes")
    # ### end Alembic commands ###
