"""Record an email address for each account

``users.email`` is nullable and stays null for every account that exists today.
Registration through the web interface requires an address, but `altero user
add` does not and never will: an account that only ever syncs with an API key
has no use for one, and making the column NOT NULL would mean inventing
addresses for accounts that already work.

Revision ID: cf1c30dc2b55
Revises: 707f2c15ddb5
Create Date: 2026-08-03 15:08:30.388920

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf1c30dc2b55"
down_revision: str | Sequence[str] | None = "707f2c15ddb5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("expires", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("email_verifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_email_verifications_expires"), ["expires"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_email_verifications_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_email_verifications_user_id"), ["user_id"], unique=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(length=320), nullable=True))
        batch_op.add_column(sa.Column("email_verified", sa.DateTime(), nullable=True))
        # Named explicitly: autogenerate emits None, and SQLite's batch mode
        # rebuilds the table from the constraint list, where an anonymous one
        # raises "Constraint must have a name".
        batch_op.create_unique_constraint("uq_users_email", ["email"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_email", type_="unique")
        batch_op.drop_column("email_verified")
        batch_op.drop_column("email")

    with op.batch_alter_table("email_verifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_verifications_user_id"))
        batch_op.drop_index(batch_op.f("ix_email_verifications_token_hash"))
        batch_op.drop_index(batch_op.f("ix_email_verifications_expires"))

    op.drop_table("email_verifications")
    # ### end Alembic commands ###
