"""Widen the upload mtime past 32 bits

The client sends an attachment's mtime as milliseconds since the epoch. That
stopped fitting in a signed 32-bit integer in January 1970, so on PostgreSQL --
where INTEGER means 32-bit -- every authorisation of a file upload failed with
"value out of int32 range". SQLite's INTEGER is 64-bit and took it happily,
which is why the tests were green and the container could not sync a single
attachment.

filesize goes with it. Nothing in range depends on that: an upload is capped at
a gibibyte in api/routes/files.py, well inside 32 bits. But that cap is a
constant in an unrelated module, and this column should not be the thing that
breaks if somebody raises it.

Rows already stored keep their values; only the column type changes.

Revision ID: db4b448ae715
Revises: 5452707b9c08
Create Date: 2026-08-03 23:59:16.310806

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db4b448ae715"
down_revision: str | Sequence[str] | None = "5452707b9c08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("storage_uploads", schema=None) as batch_op:
        batch_op.alter_column(
            "filesize", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False
        )
        batch_op.alter_column(
            "mtime", existing_type=sa.INTEGER(), type_=sa.BigInteger(), existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("storage_uploads", schema=None) as batch_op:
        batch_op.alter_column(
            "mtime", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False
        )
        batch_op.alter_column(
            "filesize", existing_type=sa.BigInteger(), type_=sa.INTEGER(), existing_nullable=False
        )

    # ### end Alembic commands ###
