"""Record group library activity for notifying members

Revision ID: ff95529bd1a0
Revises: e093f2689727
Create Date: 2026-08-05 15:33:29.746633

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff95529bd1a0"
down_revision: str | Sequence[str] | None = "e093f2689727"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_activity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("library_id", sa.Integer(), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("flushed", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["libraries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("group_activity", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_group_activity_created"), ["created"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_group_activity_library_id"), ["library_id"], unique=False
        )
        batch_op.create_index(
            "ix_group_activity_pending", ["flushed", "library_id", "created"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_activity", schema=None) as batch_op:
        batch_op.drop_index("ix_group_activity_pending")
        batch_op.drop_index(batch_op.f("ix_group_activity_library_id"))
        batch_op.drop_index(batch_op.f("ix_group_activity_created"))

    op.drop_table("group_activity")
    # ### end Alembic commands ###
